"""
train.py
--------
Training script for AnnulusPlaneNet.

Usage
-----
# Overfit test on 1 patient (what your supervisor asked for):
python train.py \
    --root_path /path/to/data \
    --train_ids CONTCT_R_08_FBA \
    --val_ids   CONTCT_R_08_FBA \
    --epochs 300 \
    --target_size 64 \
    --run_name overfit_test

# Full training:
python train.py \
    --root_path /path/to/data \
    --train_ids CONTCT_R_08_FBA CONTCT_R_09_FBA D1 D2 \
    --val_ids   CONTCT_R_16_FBA D15 \
    --epochs 500 \
    --target_size 64 \
    --run_name full_run_v1
"""

import os
import argparse
import json
import time

import numpy as np
import torch
import torch.optim as optim
from torch.optim.lr_scheduler import CosineAnnealingLR

try:
    import wandb
except:
    wandb = None

from src.dataset import create_data_loaders
from src.model   import AnnulusPlaneNet, count_parameters
from src.loss    import PlaneLoss, angle_error_degrees, centre_distance_voxels


# ---------------------------------------------------------------------------
# Argument parsing
# ---------------------------------------------------------------------------

def parse_args():
    p = argparse.ArgumentParser(
        description='Train AnnulusPlaneNet for aortic annulus localisation'
    )

    # Data
    p.add_argument('--root_path',  type=str, required=True,
                   help='Root path to processed CT data')
    p.add_argument('--train_ids',  nargs='+', required=False, default=None,
                   help='Patient IDs for training')
    p.add_argument('--val_ids',    nargs='+', required=False, default=None,
                   help='Patient IDs for validation')
    p.add_argument('--test_ids',   nargs='*', default=[],
                   help='Patient IDs for final test (optional)')

    # Model / training
    p.add_argument('--target_size', type=int, default=64,
                   help='Cubic resize dimension for input volumes')
    p.add_argument('--batch_size',  type=int, default=2)
    p.add_argument('--epochs',      type=int, default=300)
    p.add_argument('--lr',          type=float, default=1e-3)
    p.add_argument('--dropout',     type=float, default=0.3)
    p.add_argument('--use_se',     action='store_true', default=False,
                   help='Enable SE attention blocks (Stage 2); omit for vanilla baseline')
    p.add_argument('--use_cbam',   action='store_true', default=False,
                   help='Enable CBAM attention blocks (Stage 3)')
    p.add_argument('--use_coordconv', action='store_true', default=False,
                   help='Replace stem conv with CoordConv3D (CoordConv paper, arXiv:1807.03247)')
    p.add_argument('--coordconv_r', action='store_true', default=False,
                   help='Add radial-distance channel to CoordConv3D (only used if --use_coordconv)')
    p.add_argument('--w_normal',    type=float, default=1.0,
                   help='Weight for angular normal loss')
    p.add_argument('--w_centre',    type=float, default=1.0,
                   help='Weight for centre MSE loss')
    p.add_argument('--seed',        type=int, default=42)

    # 5-fold CV
    p.add_argument('--fold',        type=int, default=None,
                   help='Fold index 0-4 to use from fold_config.json')
    p.add_argument('--fold_config', type=str, default='fold_config.json',
                   help='Path to fold_config.json generated by fold split script')
    p.add_argument('--manifest_path', type=str, default=None,
                   help='Path to dataset manifest CSV')

    # Checkpoint / logging
    p.add_argument('--run_name',    type=str, default='annulus_run',
                   help='Name shown in WandB and used for checkpoint files')
    p.add_argument('--save_dir',    type=str, default='./models',
                   help='Directory to save model checkpoints')
    p.add_argument('--resume',      type=str, default=None,
                   help='Path to checkpoint to resume from')
    p.add_argument('--wandb_project', type=str, default='AnnulusPlaneDetector',
                   help='WandB project name')
    p.add_argument('--no_wandb',    action='store_true',
                   help='Disable WandB logging (useful for offline debugging)')
    p.add_argument('--patience',    type=int, default=60,
                   help='Early stopping patience (epochs without improvement)')

    return p.parse_args()


# ---------------------------------------------------------------------------
# One epoch of training
# ---------------------------------------------------------------------------

def train_one_epoch(model, loader, optimizer, loss_fn, device, image_size):
    model.train()

    total_loss   = 0.0
    total_angle  = 0.0
    total_centre = 0.0
    n_batches    = 0

    for imgs, targets, _ in loader:
        imgs    = imgs.to(device)
        targets = targets.to(device)

        optimizer.zero_grad()
        preds = model(imgs)
        loss, components = loss_fn(preds, targets)
        loss.backward()
        # Gradient clipping to prevent exploding gradients
        torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)
        optimizer.step()

        total_loss   += components['total']
        total_angle  += components['angular']
        total_centre += components['centre']
        n_batches    += 1

    return {
        'loss'       : total_loss   / n_batches,
        'angular'    : total_angle  / n_batches,
        'centre_mse' : total_centre / n_batches,
    }


# ---------------------------------------------------------------------------
# One epoch of validation
# ---------------------------------------------------------------------------

@torch.no_grad()
def validate(model, loader, loss_fn, device, image_size):
    model.eval()

    total_loss     = 0.0
    total_angle    = 0.0
    total_centre   = 0.0
    angle_errors   = []
    centre_dists   = []
    n_batches      = 0

    for imgs, targets, _ in loader:
        imgs    = imgs.to(device)
        targets = targets.to(device)

        preds = model(imgs)
        loss, components = loss_fn(preds, targets)

        # Metrics
        ang  = angle_error_degrees(preds[:, :3], targets[:, :3])
        dist = centre_distance_voxels(preds[:, 3:], targets[:, 3:], image_size)

        angle_errors.extend(ang.cpu().numpy().tolist())
        centre_dists.extend(dist.cpu().numpy().tolist())

        total_loss   += components['total']
        total_angle  += components['angular']
        total_centre += components['centre']
        n_batches    += 1

    return {
        'loss'             : total_loss   / n_batches,
        'angular'          : total_angle  / n_batches,
        'centre_mse'       : total_centre / n_batches,
        'angle_error_mean' : float(np.mean(angle_errors)),
        'angle_error_std'  : float(np.std(angle_errors)),
        'centre_dist_mean' : float(np.mean(centre_dists)),
        'centre_dist_std'  : float(np.std(centre_dists)),
    }


# ---------------------------------------------------------------------------
# Checkpoint helpers
# ---------------------------------------------------------------------------

def save_checkpoint(model, optimizer, scheduler, epoch, val_metrics,
                    args, path):
    torch.save({
        'epoch'               : epoch,
        'model_state_dict'    : model.state_dict(),
        'optimizer_state_dict': optimizer.state_dict(),
        'scheduler_state_dict': scheduler.state_dict(),
        'val_loss'            : val_metrics['loss'],
        'val_angle_error'     : val_metrics['angle_error_mean'],
        'val_centre_dist'     : val_metrics['centre_dist_mean'],
        'args'                : vars(args),
    }, path)


def load_checkpoint(path, model, optimizer=None, scheduler=None, device='cpu'):
    ckpt = torch.load(path, map_location=device)
    model.load_state_dict(ckpt['model_state_dict'])
    if optimizer and 'optimizer_state_dict' in ckpt:
        optimizer.load_state_dict(ckpt['optimizer_state_dict'])
    if scheduler and 'scheduler_state_dict' in ckpt:
        scheduler.load_state_dict(ckpt['scheduler_state_dict'])
    start_epoch = ckpt.get('epoch', 0) + 1
    print(f'Resumed from epoch {ckpt["epoch"]}  '
          f'(val_loss={ckpt.get("val_loss", "N/A"):.4f})')
    return start_epoch


# ---------------------------------------------------------------------------
# Main training loop
# ---------------------------------------------------------------------------

def main():
    args = parse_args()

    # ---- Resolve fold if specified ----
    if args.fold is not None:
        import json as _json
        with open(args.fold_config) as _f:
            _fc = _json.load(_f)
        _fold_data     = _fc['folds'][args.fold]
        args.train_ids = _fold_data['train']
        args.val_ids   = _fold_data['val']
        print(f'Using fold {args.fold}: train={len(args.train_ids)} val={len(args.val_ids)}')
    elif args.train_ids is None or args.val_ids is None:
        raise ValueError('Must provide either --fold or both --train_ids and --val_ids')

    # Reproducibility
    torch.manual_seed(args.seed)
    np.random.seed(args.seed)

    # Directories
    os.makedirs(args.save_dir, exist_ok=True)
    best_ckpt_path = os.path.join(args.save_dir, f'{args.run_name}_best.pth')
    last_ckpt_path = os.path.join(args.save_dir, f'{args.run_name}_last.pth')

    # ---- WandB ----
    use_wandb = not args.no_wandb
    if use_wandb:
        wandb.init(
            project = args.wandb_project,
            name    = args.run_name,
            config  = vars(args),
        )
        print(f'WandB run: {wandb.run.url}')
    else:
        print('WandB disabled — logging to console only')

    # ---- Data ----
    test_ids = args.test_ids if args.test_ids else args.val_ids
    train_loader, val_loader, test_loader = create_data_loaders(
        args.root_path,
        args.train_ids,
        args.val_ids,
        test_ids,
        target_size = args.target_size,
        batch_size  = args.batch_size,
        manifest_path = args.manifest_path,
    )

    # ---- Model ----
    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
    print(f'Device: {device}')

    model   = AnnulusPlaneNet(dropout_p=args.dropout, use_se=args.use_se, use_cbam=args.use_cbam, use_coordconv=args.use_coordconv, coordconv_r=args.coordconv_r).to(device)
    loss_fn = PlaneLoss(w_normal=args.w_normal, w_centre=args.w_centre)

    print(f'Model parameters: {count_parameters(model):,}')
    if use_wandb:
        wandb.watch(model, log='gradients', log_freq=50)

    # ---- Optimiser & scheduler ----
    optimizer = optim.Adam(model.parameters(), lr=args.lr, weight_decay=1e-5)
    scheduler = CosineAnnealingLR(optimizer, T_max=args.epochs, eta_min=1e-6)

    # ---- Resume ----
    start_epoch = 0
    if args.resume and os.path.exists(args.resume):
        start_epoch = load_checkpoint(
            args.resume, model, optimizer, scheduler, device
        )

    # ---- Training loop ----
    best_val_loss    = float('inf')
    patience_counter = 0

    print('\n' + '=' * 65)
    print(f'  Training: {args.run_name}')
    print(f'  Train IDs : {args.train_ids}')
    print(f'  Val IDs   : {args.val_ids}')
    print(f'  Epochs    : {args.epochs}   Batch: {args.batch_size}   LR: {args.lr}')
    print(f'  Size      : {args.target_size}³')
    print('=' * 65 + '\n')

    for epoch in range(start_epoch, args.epochs):
        t0 = time.time()

        # Train
        train_metrics = train_one_epoch(
            model, train_loader, optimizer, loss_fn, device, args.target_size
        )

        # Validate
        val_metrics = validate(
            model, val_loader, loss_fn, device, args.target_size
        )

        scheduler.step()

        elapsed = time.time() - t0
        current_lr = scheduler.get_last_lr()[0]

        # ---- Console log ----
        print(
            f'Ep {epoch+1:04d}/{args.epochs} '
            f'| train_loss {train_metrics["loss"]:.4f} '
            f'| val_loss {val_metrics["loss"]:.4f} '
            f'| angle {val_metrics["angle_error_mean"]:.2f}° '
            f'| centre {val_metrics["centre_dist_mean"]:.2f}vx '
            f'| lr {current_lr:.2e} '
            f'| {elapsed:.1f}s'
        )

        # ---- WandB log ----
        if use_wandb:
            wandb.log({
                'epoch'                     : epoch + 1,
                'train/loss'                : train_metrics['loss'],
                'train/angular_loss'        : train_metrics['angular'],
                'train/centre_mse'          : train_metrics['centre_mse'],
                'val/loss'                  : val_metrics['loss'],
                'val/angular_loss'          : val_metrics['angular'],
                'val/centre_mse'            : val_metrics['centre_mse'],
                'val/angle_error_mean_deg'  : val_metrics['angle_error_mean'],
                'val/angle_error_std_deg'   : val_metrics['angle_error_std'],
                'val/centre_dist_mean_voxel': val_metrics['centre_dist_mean'],
                'val/centre_dist_std_voxel' : val_metrics['centre_dist_std'],
                'learning_rate'             : current_lr,
            })

        # ---- Checkpointing ----
        # Always save last
        save_checkpoint(model, optimizer, scheduler, epoch,
                        val_metrics, args, last_ckpt_path)

        # Save best
        if val_metrics['loss'] < best_val_loss:
            best_val_loss    = val_metrics['loss']
            patience_counter = 0
            save_checkpoint(model, optimizer, scheduler, epoch,
                            val_metrics, args, best_ckpt_path)
            print(f'  ★ New best val_loss = {best_val_loss:.4f}  → saved')
        else:
            patience_counter += 1

        # Early stopping
        if patience_counter >= args.patience:
            print(f'\nEarly stopping after {patience_counter} epochs without improvement.')
            break

    print('\n' + '=' * 65)
    print(f'Training finished.  Best val_loss = {best_val_loss:.4f}')
    print(f'Best checkpoint : {best_ckpt_path}')
    print('=' * 65)

    if use_wandb:
        wandb.finish()


# ---------------------------------------------------------------------------

if __name__ == '__main__':
    main()
